upstream go_alert {
    server go-alert-service:8081;
}

server {
    listen 8081;

    location /health {
        proxy_pass http://go_alert;
    }

    location / {
        proxy_pass http://go_alert;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
